./themepatcher.sh "Catppuccin Mocha" "https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Mocha"
./themepatcher.sh "Catppuccin Latte" "https://github.com/prasanthrangan/hyde-themes/tree/Catppuccin-Latte"
./themepatcher.sh "Rosé Pine" "https://github.com/prasanthrangan/hyde-themes/tree/Rose-Pine"
./themepatcher.sh "Tokyo Night" "https://github.com/prasanthrangan/hyde-themes/tree/Tokyo-Night"
./themepatcher.sh "Material Sakura" "https://github.com/prasanthrangan/hyde-themes/tree/Material-Sakura"
./themepatcher.sh "Graphite Mono" "https://github.com/prasanthrangan/hyde-themes/tree/Graphite-Mono"
./themepatcher.sh "Decay Green" "https://github.com/prasanthrangan/hyde-themes/tree/Decay-Green"
./themepatcher.sh "Edge Runner" "https://github.com/prasanthrangan/hyde-themes/tree/Edge-Runner"
./themepatcher.sh "Frosted Glass" "https://github.com/prasanthrangan/hyde-themes/tree/Frosted-Glass"
./themepatcher.sh "Gruvbox Retro" "https://github.com/prasanthrangan/hyde-themes/tree/Gruvbox-Retro"
./themepatcher.sh "Synth Wave" "https://github.com/prasanthrangan/hyde-themes/tree/Synth-Wave"
./themepatcher.sh "Nordic Blue" "https://github.com/prasanthrangan/hyde-themes/tree/Nordic-Blue"
./themepatcher.sh "AbyssGreen" "https://github.com/Itz-Abhishek-Tiwari/AbyssGreen"
./themepatcher.sh "Dracula" "https://github.com/RAprogramm/HyDe-Themes/tree/Dracula"
./themepatcher.sh "Green Lush" "https://github.com/abenezerw/Green-Lush"
./themepatcher.sh "Greenify" "https://github.com/mahaveergurjar/Theme-Gallery/tree/Greenify"
./themepatcher.sh "Hack the box" "https://github.com/HyDE-Project/hyde-gallery/tree/Hack-the-Box" 
./themepatcher.sh "Mac OS" "https://github.com/HyDE-Project/hyde-gallery/tree/Mac-Os"
./themepatcher.sh "Monokai" "https://github.com/mahaveergurjar/Theme-Gallery/tree/Monokai"
./themepatcher.sh "One Dark" "https://github.com/RAprogramm/HyDe-Themes/tree/One-Dark"
./themepatcher.sh "Paranoid Sweet" "https://github.com/rishav12s/Paranoid-Sweet"
./themepatcher.sh "Rain Dark" "https://github.com/rishav12s/Rain-Dark"
./themepatcher.sh "Red Stone" "https://github.com/mahaveergurjar/Theme-Gallery/tree/Red-Stone"
./themepatcher.sh "Scarlet Night" "https://github.com/abenezerw/Scarlet-Night"
./themepatcher.sh "Sci fi" "https://github.com/KaranRaval123/Sci-fi"
./themepatcher.sh "Solarized Dark" "https://github.com/rishav12s/Solarized-Dark"
./themepatcher.sh "Windows 11" "https://github.com/HyDE-Project/hyde-gallery/tree/Windows-11"